export default {
  namespaced: true,
  state() {
    return {
      products: [
        {
          id: "0001",
          src: ["0001"],
          category: "Top",
          description: "萊卡彈性寬肩開衩背心 2color",
          haveDiscount: true,
          price: 600,
          discountprice: 540,
          size: ["XL", "L", "M", "S"],
          color: ["白", "黑"],
        },
        {
          id: "0002",
          src: ["0002"],
          category: "Top",
          description: "滾邊配色泡泡背心",
          haveDiscount: false,
          price: 450,
          //   discountprice: 540,
          size: ["F"],
          color: ["綠"],
        },
        {
          id: "0003",
          src: ["0003"],
          category: "Top",
          description: "夏日推薦/半透明感柔膚上衣",
          haveDiscount: false,
          price: 400,
          //   discountprice: 540,
          size: ["F"],
          color: ["白", "奶", "灰", "黑"],
        },

        {
          id: "0004",
          src: ["0004"],
          category: "Bottom",
          description: "抽繩涼感褲",
          haveDiscount: false,
          price: 500,
          //   discountprice: 540,
          size: ["F"],
          color: ["灰"],
        },

        {
          id: "0005",
          src: ["0005", "0005-black", "0005-apricot", "0005-green"],
          category: "Bottom",
          description: "滑摩感後開衩裙",
          haveDiscount: false,
          price: 600,
          //   discountprice: 540,
          size: ["F"],
          color: ["綠", "黑", "杏"],
        },

        {
          id: "0006",
          src: ["0006"],
          category: "Outer",
          description: "寬寬鬆鬆慵懶西外套",
          haveDiscount: false,
          price: 800,
          //   discountprice: 540,
          size: ["F"],
          color: ["咖啡"],
        },

        {
          id: "0007",
          src: ["0007", "0007-grey", "0007-white"],
          category: "Top",
          description: "氧氣感澎袖長洋裝",
          haveDiscount: true,
          price: 880,
          discountprice: 800,
          size: ["F"],
          color: ["白", "鐵灰"],
        },

        {
          id: "0009",
          src: ["0009", "0009-1", "0009-2"],
          category: "Accessories",
          description: "韓國/配色中筒厚襪",
          haveDiscount: false,
          price: 150,
          //   discountprice: 800,
          size: ["F"],
          color: ["黑", "灰"],
        },
        {
          id: "0010",
          src: ["0010", "0010-1", "0010-2"],
          category: "Shoes",
          description: "韓國/方頭低跟短靴",
          haveDiscount: false,
          price: 150,
          //   discountprice: 800,
          size: ["36", "37", "38", "39"],
          color: ["黑", "咖啡"],
        },
        {
          id: "0011",
          src: ["0011"],
          category: "Accessories",
          description: "提編織小包",
          haveDiscount: true,
          price: 550,
          discountprice: 500,
          size: ["F"],
          color: ["藍"],
        },
        {
          id: "0012",
          src: ["0012", "0012-white", "0012-green"],
          category: "Top",
          description: "回歸春日色系皺皺洋裝",
          haveDiscount: true,
          price: 650,
          discountprice: 520,
          size: ["F"],
          color: ["白", "綠", "黑"],
        },
        {
          id: "0013",
          src: ["0013"],
          category: "Accessories",
          description: "薄針織披肩",
          haveDiscount: false,
          price: 300,
          // discountprice: 520,
          size: ["F"],
          color: ["灰"],
        },
        {
          id: "0014",
          src: ["0014", "0014-black", "0014-purple"],
          category: "Bottom",
          description: "極長裙今年必敗",
          haveDiscount: true,
          price: 600,
          discountprice: 570,
          size: ["F"],
          color: ["白", "黑", "紫"],
        },
        {
          id: "0015",
          src: ["0015", "0015-black", "0015-green"],
          category: "Outer",
          description: "薄款長袖短版西外",
          haveDiscount: false,
          price: 550,
          // discountprice: 570,
          size: ["F"],
          color: ["灰藍", "黑", "綠"],
        },
        {
          id: "0016",
          src: ["0016", "0016-1"],
          category: "Top",
          description: "格紋荷葉領上衣",
          haveDiscount: false,
          price: 500,
          // discountprice: 570,
          size: ["F"],
          color: ["灰"],
        },
        {
          id: "0017",
          src: ["0017", "0017-1", "0017-2"],
          category: "Bottom",
          description: "減齡直筒牛仔吊帶褲",
          haveDiscount: true,
          price: 800,
          discountprice: 770,
          size: ["F"],
          color: ["藍"],
        },
      ],
    };
  },
  actions: {},
  mutations: {},
  getters: {
    getProducts(state) {
      return state.products;
    },
  },
};
